yarnPath: .yarn/releases/yarn-3.3.1.cjs

nodeLinker: node-modules

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'

  cpu:
    - 'current'
    - 'x86'
    - 'x64'
    - 'arm64'
    - 'ia32'
